Vagrant.configure("2") do |config|
  config.vm.box = "debian/bullseye64"

  config.vm.provider "virtualbox" do |v|
    v.name = "stage2-final-task"
    v.memory = 3072
    v.cpus = 2
  end

  config.vm.provision "shell", path: "vagrant_provision.sh", privileged: false
end
